config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'pages#home'

  resources :spaces, only: [ :new, :index, :show, :create, :destroy ] do
    resources :bookings, only: [ :new, :index, :create ]
  end
  resources :spaces, only: [ :new, :index, :show, :create, :destroy ] do
      resources :reviews, only: :create
  end
  resources :bookings, only: [ :show, :destroy ]
  resources :reviews, only: :destroy
  resources :users, only: :show
  mount Attachinary::Engine => "/attachinary"
  #resources :bookings, only: [ :new, :index, :show, :create ]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :space
  belongs_to :user
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :space
end

app/models/space.rb
class Space < ApplicationRecord
  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_many :reviews, dependent: :destroy

  has_attachment :photo

  geocoded_by :address
  after_validation :geocode, if: :address_changed?
  validates :photo, presence: true
  validates :description, presence: true
  validates :price_by_day, presence: true
  validates :name, presence: true
  validates :address, presence: true
  validates :size, presence: true
  validates :plugs, presence: true
  validates :windows, presence: true
  validates :wc, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, omniauth_providers: [:facebook]

  has_many :spaces
  has_many :bookings

  def self.find_for_facebook_oauth(auth)
      user_params = auth.slice(:provider, :uid)
      user_params.merge! auth.info.slice(:email, :first_name, :last_name)
      user_params[:facebook_picture_url] = auth.info.image
      user_params[:token] = auth.credentials.token
      user_params[:token_expiry] = Time.at(auth.credentials.expires_at)
      user_params = user_params.to_h

      user = User.where(provider: auth.provider, uid: auth.uid).first
      user ||= User.where(email: auth.info.email).first # User did a regular sign up in the past.
      if user
        user.update(user_params)
      else
        user = User.new(user_params)
        user.password = Devise.friendly_token[0,20]  # Fake password for validation
        user.save
      end

    return user
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_action :authenticate_user!
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def index
    @bookings = Booking.all
  end

  def show
    @booking = Booking.find(params[:id])
  end

  def new
    @space = Space.find(params[:space_id])
    @booking = Booking.new
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.user = current_user
    @booking.space = Space.find(params[:space_id])
    @price = @booking.space.price_by_day
    @time = @booking.duration
    @booking.price = @price * @time
    @start = @booking.start_day
    @booking.end_day = @start + @time
    if @booking.save
      redirect_to booking_path(@booking)
    else
      render 'new'
    end
  end

  def destroy
     @booking = Booking.find(params[:id])
     @booking.destroy
     redirect_to user_path(current_user)
  end

  private

  def booking_params
    params.require(:booking).permit(:start_day, :duration, :price, :end_day)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]
  def home
    @spaces = Space.all
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def create
    @space = Space.find(params[:space_id])
    @review = Review.new(review_params)
    @review.space = @space
    if @review.save
      respond_to do |format|
        format.html { redirect_to space_path(@space) }
        format.js
      end
    else
      respond_to do |format|
        format.html { render 'spaces/show' }
        format.js
    end
  end
end

def destroy
  @review = Review.find(params[:id])
  @space = @review.space
  @review_id = @review.id
  @review.destroy
  respond_to do |format|
    format.html {redirect_to space_path(@space)}
    format.js {}
  end
end

  private
  def review_params
    params.require(:review).permit(:rating, :comment)
  end
end

app/controllers/spaces_controller.rb
class SpacesController < ApplicationController
    skip_before_action :authenticate_user!, only: [ :index, :show ]

  def index
    @spaces = Space.all
    @space = Space.where.not(latitude: nil, longitude: nil)
    @hash = Gmaps4rails.build_markers(@space) do |space, marker|
      marker.lat space.latitude
      marker.lng space.longitude
      # marker.infowindow render_to_string(partial: "/flats/map_box", locals: { flat: flat })
    end
  end

  def new
    @space = Space.new
  end

  def show
    @space = Space.find(params[:id])
    @review = Review.new
    @space_coordinates = { lat: @space.latitude, lng: @space.longitude }
    @spaces = Space.where.not(latitude: nil, longitude: nil)
    @hash = Gmaps4rails.build_markers(@space) do |space, marker|
      marker.lat space.latitude
      marker.lng space.longitude
      # marker.infowindow render_to_string(partial: "/flats/map_box", locals: { flat: flat })
    end
  end

  def create
    @space = Space.new(space_params)
    @space.user = current_user
    if @space.save
      redirect_to space_path(@space)
    else
      render :new
    end
  end

  def destroy
     @space = Space.find(params[:id])
     @space.destroy
     redirect_to user_path(current_user)
  end

  private

  def space_params
    params.require(:space).permit(:name, :address, :size, :price_by_day, :photo, :wc, :nails, :drill, :plugs, :windows, :description)
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    user = User.find_for_facebook_oauth(request.env['omniauth.auth'])

    if user.persisted?
      sign_in_and_redirect user, event: :authentication
      set_flash_message(:notice, :success, kind: 'Facebook') if is_navigational_format?
    else
      session['devise.facebook_data'] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @bookings = @user.bookings
    @spaces = @user.spaces
    @owner_bookings = Booking.where(space: @spaces)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <h2>Booking : <%= @space.name %></h2>
      <hr id="hrspecial">
      <%= simple_form_for [@space, @booking] do |f|%>
      <div class="form-inputs">
        <%= f.input :start_day %>
        <hr id="hrspecial">
        <%= f.input :duration %>
      </div>
      <div class="row">
        <div class="col-md-12 text-center">
        <hr id="hrspecial">
          <%= f.submit "book" ,class: "btn", id:"signup" %>
        </div>
      </div>
     <% end %>
    </div>
  </div>
</div>

app/views/bookings/show.html.erb
<div id="bannerBooked" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= cl_image_path @booking.space.photo.path %>')">
  <div class="banner-content text-center">
    <h2>Congratulations,<br>You've just booked <%= @booking.space.name %>! </h2>
  </div>
</div>
<div id="colorBox">
  <p class="text-center" id="yourRecap">Recap for your booking:</p>
</div>


<div class="RecapWrapper flexbox">
  <div class="StartDateBigContainer">
    <div class="StartDateContainer">
      <div class="StartDateLabel">
        <p class="headerRecap">Start date</p>
      </div>
        <div class="StartDateSubtitle">
          <p class="subtitle"><%= @booking.start_day.strftime("%A %d %B") %>
          </p>
        </div>
    </div>
  </div>
  <div class="EndDateBigContainer">
    <div class="EndDateContainer">
      <div class="EndDateLabel">
        <p class="headerRecap">End date</p>
      </div>
        <div class="EndDateSubtitle">
          <p class="subtitle"><%= @booking.end_day.strftime("%A %d %B") %></p>
        </div>
    </div>
  </div>
  <div class="DurationBigContainer">
    <div class="DurationContainer">
      <div class="DurationLabel">
        <p class="headerRecap">Duration</p>
      </div>
        <div class="DurationSubtitle">
          <p class="subtitle"><%= @booking.duration %></p>
        </div>
    </div>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="col-md-8">
      <div class="row">
        <div class="col-md-6 no-padding-left">
          <h3>About the place:</h3>
          <p class="text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quod minus laboriosam, reprehenderit animi sequi error omnis.</p>
        </div>
        <div class="col-md-6">
          <h3>Cancellation policy:</h3>
          <p class="text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Numquam  alias minus, sapiente aliquam aperiam mollitia quas at quibusdam perspiciatis ipsa officiis illum quasi rerum.</p>
        </div>
      </div>
    <div class="row">
      <div class="col-md-6 no-padding-left">
        <h3>Security deposit:</h3>
        <p class="text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Est deleniti nam, nisi quae delectus adipisci voluptatibus ea voluptate sunt, at iste fugit.</p>
      </div>
      <div class="col-md-6">
        <h3>Payement:</h3>
        <p class="text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Est deleniti nam, nisi quae delectus adipisci voluptatibus ea voluptate sunt, at iste fugit.</p>
      </div>
    </div>
    </div>
    <div class="col-md-4 no-padding-right">
      <h3 id="payout">Payout:</h3>
      <div class="col-md-6 no-padding-left">
        <p>€<%= @booking.space.price_by_day %> x <%= @booking.duration %>days</p>
        <p>Curate Service Fee</p>
        <p>Total Payout</p>
      </div>
      <div class="col-md-6 rightAlign" id="price">
        <p><%= @booking.price %>€</p>
        <p><%= @booking.space.price_by_day %>€</p>
        <p><%= @booking.price + @booking.space.price_by_day%>€</p>
      </div>
    </div>
  </div>
</div>
<!-- <p>For <%= @booking.price %> €</p>
<p><%= link_to "Back to spaces", spaces_path %></p> -->

app/views/pages/home.html.erb
<div class="banner">
  <div class="banner-content text-center">
  <%= image_tag "logo.png", class: "logo" %>
    <h1>Find venues to curate your events!</h1>
    <div class="searchBarWrapper"><!-- react-empty: 138 -->
      <%= simple_form_for :space, url: spaces_path, method: :get, html: { class:"flexbox" } do |f|%>
        <div class="searchContainer">
          <div class="locationContainer" style="width:100%;">
            <div class="containerLocationLabel">Where </div>
              <div class="containerLocationSubtitle" id="homeform">
                  <%= f.input :address, class:'locationInput', placeholder: 'Location', label: false %>
              </div>
              <div class="Underline">
            </div>
          </div>
        </div>
        <div class="searchDateContainer">
          <div class="dateContainer" style="width:100%;">
            <div class="containerDateLabel">When</div>
              <div class="container_datepicker">
                <input type="date" placeholder="Dates" class="dateInput">
              </div>
            <div class="Underline"></div>
          </div>
        </div>
        <div class="searchButtonContainer">
          <div class="buttonContainer" style="width:100%;">
              <%= f.submit "Search", class: 'btn btn-sm' %>
           <!--  </button> -->
            <div class="Underline"></div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

<h2 class="text-center" id="phrase">How does it work ?</h2>

<div class="container text-center padded features">
  <div class="row">
    <div class="col-xs-12 col-sm-4">
      <%= image_tag "research.png", class: "icons" %>
      <p class="icons-text"><strong>Find the best spot according to your needs.</strong></p>
    </div>
    <div class="col-xs-12 col-sm-4">
      <%= image_tag "envelope.png", class: "icons" %>
      <p class="icons-text"><strong>Contact the owner and book the place for as long as you need.</strong></p>
    </div>
    <div class="col-xs-12 col-sm-4">
      <%= image_tag "museum.png", class: "icons" %>
      <p class="icons-text"><strong>Enjoy your professional exhibition!</strong></p>
    </div>
  </div>
</div>

<!-- ________________CARD CAROUSEL SLICK________________ -->
<div id="carousel-container">
  <div id="title-carousel">Our latest venues</div>
  <div id="carousel-content">
    <div class="autoplay" id="card-slider">
      <div class="card margin-left" style="height: 300px; background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= image_path('1.jpg') %>')"></div>
      <div class="card margin-left" style="height: 300px; background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= image_path('2.jpg') %>')"></div>
      <div class="card margin-left" style="height: 300px; background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= image_path('3.jpg') %>')"></div>
      <div class="card margin-left" style="height: 300px; background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= image_path('1.jpg') %>')"></div>
      <div class="card margin-left" style="height: 300px; background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= image_path('2.jpg') %>')"></div>
      <div class="card margin-left" style="height: 300px; background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= image_path('3.jpg') %>')"></div>
    </div>
  </div>
</div>

<% content_for :after_js do %>
  <script>
    $('.autoplay').slick({
      slidesToShow: 3,
      slidesToScroll: 1,
      autoplay: true,
      autoplaySpeed: 3000,
      nextArrow: '<i class="fa fa-angle-right fa-2x next"></i>',
      prevArrow: '<i class="fa fa-angle-left fa-2x prev"></i>',
    });
  </script>
<% end %>

<br>

app/views/reviews/_form.html.erb
<%= simple_form_for([ space, review ], remote: true) do |form| %>
  <%= form.input :comment, as: :text %>
  <%= form.button :submit %>
<% end %>

app/views/reviews/_show.html.erb
<div class="media" data-review-id="<%= review.id %>">
    <div class="row">
    <div class="col-md-2">
      <%= link_to user_path(current_user) do %>
      <% avatar_url = current_user.facebook_picture_url || "http://placehold.it/30x30" %>
      <%= image_tag avatar_url, class: "avatar-large", id: "navbar-wagon-menu" %>
      <% end %>
    </div>
    <div class="col-md-4">
      <h4 class="media-heading user_name">Me</h4>
    </div>
  </div>
  <div class="media-body">
  <div class="flex-review">
    <p style="color: black; font-size: 15px;"><%= review.comment %></p>
    <%= link_to review_path(review), method: :delete, remote: true do %>
      <i class="fa fa-trash-o fa" aria-hidden="true" style="color: black;"></i>
    <% end %>
  </div>
  </div>
</div>

app/views/reviews/create.js.erb
<% if @review.errors.any? %>
  $('#new_review').html("<%= j render 'reviews/form', space: @space, review: @review %>");
<% else %>
  var new_review = $("<%= j render 'reviews/show', review: @review %>").hide();
  $('#reviews').append(new_review);
  new_review.slideDown();
  $('#new_review').html("<%= j render 'reviews/form', space: @space, review: Review.new %>");
  $('#review_count').html('<%= j render 'spaces/review_count', reviews: @space.reviews %>')
<% end %>

app/views/reviews/destroy.js.erb
$('[data-review-id=<%= @review_id %>]').slideUp();

app/views/reviews/new.html.erb
<h1 style="text-align: center;">Reviews</h1>

<%= simple_form_for [@space, @review] do |f| %>
<%= f.input :comment %>
<%= f.input :rating %>
<%= f.button :submit, class: 'btn btn-primary' %>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo.png" %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <!-- Different navigation if login or not -->
    <% if user_signed_in? %>
        <div class="navbar-wagon-item">
            <ul class="nav nav-pills pull-left">
              <li>
                <%= link_to user_path(current_user), class: 'become_curator' do %>
                  <%= t(".profile", default: "Become a curator") %>
                <% end %>
              </li>
              <li>
                <%= link_to spaces_path, class: 'become_curator' do %>
                  <%= t(".profile", default: "Venues") %>
                <% end %>
              </li>
              <li>
                <%= link_to user_path(current_user), class: 'become_curator' do %>
                  <%= t(".profile", default: "My profile") %>
                <% end %>
              </li>
              <li>
                <%= link_to destroy_user_session_path, method: :delete, class: 'become_curator' do %>
                  <%= t(".sign_out", default: "Log-Out") %>
                <% end %>
              </li>
            </ul>
          </div>
          <% avatar_url = current_user.facebook_picture_url || "http://placehold.it/30x30" %>
          <%= image_tag avatar_url, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
        </div>
    <% else %>
        <div class="navbar-wagon-item">
            <ul class="nav nav-pills pull-left">
              <li>
                <%= link_to new_user_session_path, class: 'become_curator' do %>
                  <%= t(".profile", default: "Become a curator") %>
                <% end %>
              </li>
              <li>
                <%= link_to spaces_path, class: 'become_curator' do %>
                  <%= t(".profile", default: "Venues") %>
                <% end %>
              </li>
              <li>
                  <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: 'become_curator' %>
              </li>
            </ul>
          </div>
        </div>

    <% end %>

  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Become a curator</a></li>
        <li><a href="#">Sign up</a></li>
        <li><a href="#">Help</a></li>
        <li><a href="#">My profile</a></li>
      </ul>
    </div>
  </div>
</div>

app/views/spaces/_review_count.html.erb
<h2><%= pluralize reviews.size, "review" %></h2>

app/views/spaces/index.html.erb
<div class="wrapper search">
<div class="col-md-8">
    <div ><!-- react-empty: 138 -->
      <%= simple_form_for :space, url: spaces_path, method: :get, html: { class:"flexbox" } do |f|%>
        <div class="searchContainer">
          <div class="locationContainer" style="width:100%;">
              <div class="containerLocationSubtitle" id="special">
                <%= f.input :name, class:'locationInput', placeholder: 'Location', label: false %>
              </div>
              <div class="Underline">
            </div>
          </div>
        </div>
        <div class="searchDateContainer">
          <div class="dateContainer" style="width:100%;">
              <div class="container_datepicker">
                <input type="date" placeholder="Dates" class="dateInput">
              </div>
            <div class="Underline"></div>
          </div>
        </div>
        <div class="searchButtonContainer">
          <div class="buttonContainer" style="width:100%;">
              <%= f.submit "Search", class: 'btn btn-sm' %>
           <!--  </button> -->
            <div class="Underline"></div>
          </div>
        </div>
      <% end %>
    </div>
    </div>
  </div>
</div>
<div>
  <div class="row specialrow">
    <div class="col-xs-12 col-sm-8 col-md-8 column">
      <div class="wrapper scrollcard">
        <div class="col-xs-12 col-md-6">
          <%= image_tag "add-v.jpg", class: "venue-add" %>
          <h2 class="add-description">Add a venue</h2>
          <%= link_to "", new_space_path, class: "card-link" %>
        </div>
        <% @spaces.each do |space| %>
        <div class="col-xs-12 col-md-6">
          <%if space.photo? %>
          <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= cl_image_path space.photo.path, height: 300, width: 400, crop: :fill %>')"></div>
          <% else %>
          <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= image_path('noimage.jpg') %>')"></div>
          <% end %>
          <h2 class="card-description"><%= space.price_by_day %>€</h2>
          <h2><%= space.name %></h2>
          <h5>Surface: <%= space.size %>m² - <%= space.address %></h5>
          <%= link_to "", space_path(space), class: "card-link" %>
        </div>
        <% end %>
      </div>
    </div>
    <div class="col-xs-12 col-sm-4 col-md-4 column">
      <div id="map" style="width: 100%; height: 90vh;"></div>
    </div>
  </div>
</div>


<% content_for(:after_js) do %>
<%= javascript_tag do %>
$(document).ready(function() {
var handler = Gmaps.build('Google');
handler.buildMap({ internal: { id: 'map' } }, function() {
markers = handler.addMarkers(<%= raw @hash.to_json %>);
handler.bounds.extendWith(markers);
handler.fitMapToBounds();
if (markers.length == 0) {
handler.getMap().setZoom(2);
} else if (markers.length == 1) {
handler.getMap().setZoom(14);
}
});
});
<% end %>
<% end %>

app/views/spaces/new.html.erb
<div>
  <p class="rightAlign rightTag"><%= link_to "Go back to venues", spaces_path %></p>
</div>
<div class="form-style flexbox">
  <%= simple_form_for @space do |f| %>
  <div class="row">
    <div class="col-md-12">
      <%= f.input :name %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <%= f.input :address %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12" id="description">
    <%= f.input :description %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6">
      <%= f.input :size %>
    </div>
    <div class="col-md-6">
      <%= f.input :price_by_day %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-offset-2 col-md-2">
      <%= f.input :nails %>
    </div>
    <div class="col-md-offset-4 col-md-2">
      <%= f.input :drill %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-4">
      <%= f.input :plugs %>
    </div>
    <div class="col-md-4">
      <%= f.input :windows %>
    </div>
    <div class="col-md-4">
      <%= f.input :wc %>
    </div>
  </div>
    <div class="row">
      <div class="col-md-12">
        <%= f.input :photo, as: :attachinary %>
      </div>
    </div>
    <div class="row">
      <div class="col-md-offset-4 col-md-4">
        <%= f.button :submit, class: 'btn btn-primary' %>
      </div>
    </div>
  <% end %>
</div>
<br>

app/views/spaces/show.html.erb
<div class="jumbotron" style="background-image: url('<%= cl_image_path(@space.photo.path) %>');">
  <div class="container">
    <div class="content">
      <h1><%= @space.name %></h1>
    </div>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sd-10 col-sm-offset-1">
      <hr>
      <div class="row">
        <div class="col-md-6">
          <h2>About this venue</h2>
          <p><%= @space.description %></p>
        </div>
        <div class="col-md-4">
          <ul class="list-click pull-right">
            <li>
              <%= link_to "Book", new_space_booking_path(@space), class: "btn btn-primary" %>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>

<div id="venue-description">
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-sd-10 col-sm-offset-1">
        <hr>
        <h3><%= @space.address %></h3>
        <hr>
        <div class="row" id="venue-data">
          <div class="col-xs-12 col-sd-3 col-md-3">
            <p><strong>Venue details</strong></p>
          </div>
          <div class="col-xs-12 col-sd-4 col-md-4">
            <p><i class="fa fa-arrows-alt" aria-hidden="true"></i> - Venue size : <strong><%= @space.size %> m²</strong></p>
            <p><i class="fa fa-money" aria-hidden="true"></i> - Venue price : <strong><%= @space.price_by_day %> €/jour</strong></p>
            <p><i class="fa fa-map-pin" aria-hidden="true"></i> - nails: <strong><% if @space.nails? %>yes <% else %>no <% end %></strong> </p>
            <p><i class="fa fa-wrench" aria-hidden="true"></i> - drill: <strong><% if @space.drill? %>yes <% else %>no <% end %></strong></p>
          </div>
          <div class="col-xs-12 col-sd-4 col-md-4">
            <p><i class="fa fa-plug" aria-hidden="true"></i> - Available plugs: <strong><%= @space.plugs %></strong></p>
            <p><i class="fa fa-windows" aria-hidden="true"></i> - Number of Windows: <strong><%= @space.windows %></strong></p>
            <p><i class="fa fa-male" aria-hidden="true"></i><i class="fa fa-female" aria-hidden="true"></i> - Number of WC: <strong><%= @space.wc %></strong></p>
          </div>
        </div>
        <hr>
          <div class="col-md-offset-1 col-md-10">
          <div id="map" style="width: 80%; height: 300px;">
         </div>
         </div>
      </div>
    </div>
  </div>
</div>

<div id="venue-description">
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-sd-10 col-sm-offset-1">

<!-- Form ADD Review   -->
<% if current_user %>
  <div class="container">
     <div class="row">
       <div class="col-md_8">
         <%= render 'reviews/form', space: @space, review: @review %>
       </div>
     </div>
   </div>
<% end %>

        <!-- Form  Review Display -->

        <div class="container">
            <div class="row">
              <div class="col-md-10">
                  <div class="page-header">
                    <div id="review_count">
                      <%= render 'review_count', reviews: @space.reviews %>
                    </div>
                  </div>
                  <div class="comments-list" id="reviews">
                  <% if @space.reviews.blank? %>
                        Please write the first review for <%= @space.name %>
                  <% else %>
                    <% @space.reviews.each do |review| %>
                        <%= render 'reviews/show', review: review %>
                    <% end %>
                  <% end %>
                  </div>
                </div>
            </div>
        </div>
      </div>
    </div>
  </div>
</div>

<!-- JS SCRIPT -->

<% content_for(:after_js) do %>
  <%= javascript_tag do %>
    $(document).ready(function() {
      var handler = Gmaps.build('Google');
      handler.buildMap({ internal: { id: 'map' },
       provider : { scrollwheel: false } },
       function() {
        markers = handler.addMarkers(<%= raw @hash.to_json %>);
        handler.bounds.extendWith(markers);
        handler.fitMapToBounds();
        if (markers.length == 0) {
          handler.getMap().setZoom(2);
        } else if (markers.length == 1) {
          handler.getMap().setZoom(15);
        }
      });
    });
    <% end %>
    <% end %>